### ISSUE TITLE
Mouse button support

### ISSUE THREAD

**Issue by Empoga** [StrateimTech/HID-API#1]
Hello again!
So I really liked your rust project but then found the same in c#, which is way more suitable for me for adding additional functionality. 
I tried to apply the changes for mouse 4 & 5 from your rust project to the c# one. Unfortunately I failed and only got crashes. Is there any chance you can add support for mouse 4& 5 on this project as well?
 I am sorry to basically ask the same question twice. We are creating a game like experience for older people and it is just way easier for me to add additional functionality in c# than in rust.

**Comment by Empoga** [comment]
Semms like you are busy, totally understand that. Maybe you can lead me into the right direction.
I have check the bits on 0x10 and 0x20 in byteArray 3. they never switch when pressing mouse 4 or 5 button. They do switch however when I use the scrol wheel.

**Comment by EthoIRL** [comment]
Oh my I'm so sorry I didn't see your issue until today... I'll get that ported over asap.
